DELIMITER //
 CREATE PROCEDURE GETHIGHSALARY(IN MIN_SALARY INT)
BEGIN
   SELECT EMP_NAME, SALARY
        FROM EMPLOYEES
       WHERE SALARY > MIN_SALARY;
END //
 DELIMITER ;
 CALL GETHIGHSALARY(40000);
 
 